### ISSUE TITLE
No

### ISSUE THREAD

**Issue by LONOAL** [SilverClick/JugandoConPullRequest#1]
Gonzalo bobo

**Comment by LONOAL** [comment]
estamos de acuerdo o no?

**Comment by SilverClick** [comment]
en que

**Comment by SilverClick** [comment]
que quieres trabajador promedio

**Comment by LONOAL** [comment]
en que morde es un champ para platitas

**Comment by SilverClick** [comment]
trabajamos oq ue bobo

**Comment by LONOAL** [comment]
hasta que estemos de acuerdo no puedo continuar

**Comment by SilverClick** [comment]
es easy o sea que si
